name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # Change to your main branch name if different
  workflow_dispatch:    # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Keep using your self-hosted runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT for checkout
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version your project requires
          
      - name: Install pnpm
        run: npm install -g pnpm
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm run build  # Your build command
        
      - name: Configure GitHub Pages
        run: |
          # Create a .nojekyll file to bypass Jekyll processing
          touch dist/.nojekyll
          
      - name: Setup Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Deploy to GitHub Pages
        run: |
          # Set the remote URL with the token for authentication
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          
          # Create a temporary branch
          git checkout --orphan gh-pages-temp
          
          # Remove all files except the dist directory
          find . -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} \;
          
          # Move dist contents to root
          mv dist/* .
          rm -rf dist
          
          # Add all files
          git add .
          
          # Commit changes
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages-temp:gh-pages
          
          # Clean up
          git checkout -f master
          git branch -D gh-pages-temp